"""Update column in MyModel

Revision ID: 233cab050aa8
Revises: 36ad1736ead7
Create Date: 2023-10-26 20:15:24.178970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '233cab050aa8'
down_revision = '36ad1736ead7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itemsreturnedtoowner')
    op.drop_table('founditems')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('lostitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isfound', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('isreturnedtoowner', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('user_reported_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_lostitems_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_lostitems_user_reported_id_users'), 'users', ['user_reported_id'], ['id'])
        batch_op.drop_column('user_id')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rewardamount', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('lostitem_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_rewards_user_id_users', type_='foreignkey')
        batch_op.drop_constraint('fk_rewards_item_id_lostitems', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rewards_lostitem_id_lostitems'), 'lostitems', ['lostitem_id'], ['id'])
        batch_op.drop_column('item_name')
        batch_op.drop_column('item_id')
        batch_op.drop_column('user_id')
        batch_op.drop_column('reward_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reward_amount', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('item_name', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_rewards_lostitem_id_lostitems'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rewards_item_id_lostitems', 'lostitems', ['item_id'], ['id'])
        batch_op.create_foreign_key('fk_rewards_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('lostitem_id')
        batch_op.drop_column('rewardamount')

    with op.batch_alter_table('lostitems', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_lostitems_user_reported_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_lostitems_user_id_users', 'users', ['user_id'], ['id'])
        batch_op.drop_column('user_reported_id')
        batch_op.drop_column('isreturnedtoowner')
        batch_op.drop_column('isfound')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_comments_user_id_users', 'users', ['user_id'], ['id'])

    op.create_table('founditems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('item_name', sa.VARCHAR(), nullable=True),
    sa.Column('reward_id', sa.INTEGER(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['lostitems.id'], name='fk_founditems_item_id_lostitems'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_founditems_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itemsreturnedtoowner',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('datereturned', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['lostitems.id'], name='fk_itemsreturnedtoowner_item_id_lostitems'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_itemsreturnedtoowner_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
