"""model

Revision ID: 268dd3e1d2b9
Revises: ee9cf1bec13d
Create Date: 2023-11-07 12:39:02.845894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268dd3e1d2b9'
down_revision = 'ee9cf1bec13d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Integer(), nullable=True))

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_rewards_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rewards_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.drop_column('comment')

    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('comment', sa.VARCHAR(), nullable=True),
    sa.Column('lostitem_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['lostitem_id'], ['items.id'], name='fk_comments_lostitem_id_items'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
