"""comment

Revision ID: 6efaba8b651b
Revises: 7accc50353e3
Create Date: 2023-11-07 13:06:44.515282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6efaba8b651b'
down_revision = '7accc50353e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_claims_item_id_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_claims_item_name_items'), 'items', ['item_name'], ['item_name'])
        batch_op.drop_column('item_id')

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lostitem_name', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_rewards_lostitem_id_items', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rewards_lostitem_name_items'), 'items', ['lostitem_name'], ['item_name'])
        batch_op.drop_column('lostitem_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lostitem_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_rewards_lostitem_name_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rewards_lostitem_id_items', 'items', ['lostitem_id'], ['id'])
        batch_op.drop_column('lostitem_name')

    with op.batch_alter_table('claims', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_claims_item_name_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_claims_item_id_items', 'items', ['item_id'], ['id'])
        batch_op.drop_column('item_name')

    # ### end Alembic commands ###
