"""models

Revision ID: 7e91b21c6f59
Revises: 233cab050aa8
Create Date: 2023-10-30 14:00:43.524138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e91b21c6f59'
down_revision = '233cab050aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=True),
    sa.Column('item_description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('reported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('user_reported_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_reported_id'], ['users.id'], name=op.f('fk_items_user_reported_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claims',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_claims_item_id_items')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_claims_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reward_id', sa.Integer(), nullable=True),
    sa.Column('payer_user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['payer_user_id'], ['users.id'], name=op.f('fk_payments_payer_user_id_users')),
    sa.ForeignKeyConstraint(['reward_id'], ['rewards.id'], name=op.f('fk_payments_reward_id_rewards')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('lostitems')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_lostitem_id_lostitems', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_lostitem_id_items'), 'items', ['lostitem_id'], ['id'])

    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint('fk_rewards_lostitem_id_lostitems', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_rewards_lostitem_id_items'), 'items', ['lostitem_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rewards', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_rewards_lostitem_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_rewards_lostitem_id_lostitems', 'lostitems', ['lostitem_id'], ['id'])

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_lostitem_id_items'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_lostitem_id_lostitems', 'lostitems', ['lostitem_id'], ['id'])

    op.create_table('lostitems',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('isfound', sa.BOOLEAN(), nullable=True),
    sa.Column('isreturnedtoowner', sa.BOOLEAN(), nullable=True),
    sa.Column('user_reported_id', sa.INTEGER(), nullable=True),
    sa.Column('item_name', sa.VARCHAR(), nullable=True),
    sa.Column('item_description', sa.VARCHAR(), nullable=True),
    sa.Column('image_url', sa.VARCHAR(), nullable=True),
    sa.Column('reported_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['user_reported_id'], ['users.id'], name='fk_lostitems_user_reported_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('payments')
    op.drop_table('claims')
    op.drop_table('items')
    # ### end Alembic commands ###
